version: '3'
volumes:
    # 自定义数据卷
    media_vol:
    static_vol:
networks: # 自定义网络(默认桥接), 不使用links通信
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge
  redis_network:
    driver: bridge
services:
  db:
    image: mysql:8.0.34
    #command: --default-authentication-plugin=mysql_native_password --mysqlx=0
    restart: always
    volumes:
      - ./usr/local/mysql/data/:/var/lib/mysql
      - ./usr/local/mysql/log/:/var/log/mysql
      - ./usr/local/mysql/conf:/etc/mysql/conf.d
    env_file:
      - .env
    environment:
#      - MYSQL_HOST=42.192.160.232
      - MYSQL_DATABASE=hello
#      - MYSQL_ROOT=root
      - MYSQL_ROOT_PASSWORD=Chengyan#251
    networks:
      - db_network
    ports:
      - "3306:3306"
  web:
    build: .
    expose:
      - "8000"
    command: python3 manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/app
      - static_vol:/app/static
      - media_vol:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_SECRET_KEY:${DJANGO_SECRET_KEY}
      - DJANGO_SETTINGS_MODULE:${DJANGO_SETTINGS_MODULE}
      - ALLOWED_HOSTS=*
    depends_on:
      - db
    networks:
      - nginx_network
      - db_network
  nginx:
    build: ./compose/nginx
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
    volumes:
      - ./compose/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf # 挂载nginx配置文件
      - ./compose/nginx/ssl:/usr/share/nginx/ssl # 挂载ssl证书目录
      - ./compose/nginx/log:/var/log/nginx # 挂载日志
      - static_vol:/usr/share/nginx/html/static # 挂载静态文件
      - media_vol:/usr/share/nginx/html/media # 挂载用户上传媒体文件
    networks:
      - nginx_network
    depends_on:
      - web
    restart: always
