# Generated by Django 3.2.25 on 2025-04-18 20:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRClothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('icon', models.CharField(max_length=255, verbose_name='图标')),
                ('bgColor', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='背景色')),
            ],
            options={
                'verbose_name': '服装',
                'verbose_name_plural': '服装',
            },
        ),
        migrations.CreateModel(
            name='SRMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('icon', models.CharField(max_length=50, verbose_name='菜单图标')),
                ('parent_id', models.IntegerField(verbose_name='父菜单id')),
                ('order_num', models.IntegerField(verbose_name='显示顺序')),
                ('path', models.CharField(max_length=50, verbose_name='路由地址')),
                ('component', models.CharField(blank=True, max_length=50, null=True, verbose_name='组件路径')),
                ('menu_type', models.CharField(max_length=50, verbose_name='菜单类型（M 目录 C 菜单 F 按钮）')),
                ('perms', models.CharField(blank=True, max_length=50, null=True, verbose_name='权限标示')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=50, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
            },
        ),
        migrations.CreateModel(
            name='SRMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='心情')),
                ('icon', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='心情图标')),
            ],
            options={
                'verbose_name': '心情',
                'verbose_name_plural': '心情',
                'db_table': 'srmood',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SRPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='昵称')),
                ('birthday', models.DateField(default=datetime.datetime.now, verbose_name='生日')),
                ('gender', models.CharField(choices=[('1', '男'), ('2', '女')], default='', max_length=50, verbose_name='性别')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=50, region=None, unique=True, verbose_name='手机号')),
                ('avator', models.CharField(default='', error_messages={'required': '请选择头像'}, max_length=255, verbose_name='头像')),
                ('remark', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '伴侣',
                'verbose_name_plural': '伴侣',
            },
        ),
        migrations.CreateModel(
            name='SRPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='SportRecord/%Y/%m/%d', verbose_name='图片')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
            },
        ),
        migrations.CreateModel(
            name='SRProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('icon', models.CharField(default='', max_length=255, verbose_name='图标')),
                ('bgColor', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='背景色')),
            ],
            options={
                'verbose_name': '道具',
                'verbose_name_plural': '道具',
            },
        ),
        migrations.CreateModel(
            name='SRScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='分数')),
                ('score', models.SmallIntegerField(verbose_name='分数1-5')),
                ('icon', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='分数图标')),
            ],
            options={
                'verbose_name': '分数',
                'verbose_name_plural': '分数',
                'db_table': 'srscore',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SRSportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='名称')),
                ('icon', models.FileField(blank=True, null=True, upload_to='SportRecord/%Y/%m/%d', verbose_name='图标')),
            ],
            options={
                'verbose_name': '运动类型',
                'verbose_name_plural': '运动类型',
            },
        ),
        migrations.CreateModel(
            name='SRSystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='应用名称')),
                ('isInReView', models.BooleanField(verbose_name='是否在审核')),
            ],
            options={
                'verbose_name': '系统配置接口',
                'verbose_name_plural': '系统配置接口',
            },
        ),
        migrations.AlterModelOptions(
            name='sruserprofile',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AddField(
            model_name='sruserprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='sruserprofile',
            name='avator',
            field=models.CharField(default='', max_length=255, verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='sruserprofile',
            name='birthday',
            field=models.DateField(auto_now=True, verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='sruserprofile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建日期'),
        ),
        migrations.AddField(
            model_name='sruserprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', '男'), ('2', '女')], default='', max_length=50, null=True, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='sruserprofile',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='sruserprofile',
            name='password',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='sruserprofile',
            name='remark',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='sruserprofile',
            name='status',
            field=models.BooleanField(default=True, verbose_name='是否禁用 0-禁用 1-正常'),
        ),
        migrations.AddField(
            model_name='sruserprofile',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='sruserprofile',
            name='username',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='sruserprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sruserprofile',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='姓名'),
        ),
        migrations.CreateModel(
            name='SRUserSportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='行为名称')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='行为地点')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='持续时间')),
                ('type', models.CharField(blank=True, choices=[('1', '做爱'), ('2', '自慰'), ('3', '梦遗')], default='', max_length=50, null=True, verbose_name='类型')),
                ('remark', models.CharField(blank=True, max_length=50, null=True, verbose_name='备注')),
                ('measure', models.SmallIntegerField(default=0, help_text='采取的安全措施，1-无保护措施,2-安全套，3-吃药', verbose_name='安全措施')),
                ('isSender', models.BooleanField(default=True, verbose_name='是否是发起方')),
                ('isHigh', models.BooleanField(default=False, verbose_name='是否潮吹')),
                ('highTime', models.SmallIntegerField(default=0, verbose_name='高潮次数')),
                ('highTimePartner', models.SmallIntegerField(default=0, verbose_name='伴侣高潮次数')),
                ('shootPlace', models.CharField(blank=True, choices=[(1, '内射'), (2, '胸部'), (3, '嘴里'), (4, '颜射'), (5, '背上'), (6, '肚皮'), (7, '其他')], max_length=50, null=True, verbose_name='射精位置')),
                ('clothings', models.ManyToManyField(blank=True, default=None, null=True, related_name='records', to='SportRecord.SRClothing', verbose_name='服装')),
                ('mood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='SportRecord.srmood', verbose_name='心情')),
                ('partner', models.ManyToManyField(blank=True, null=True, related_name='records', to='SportRecord.SRPartner', verbose_name='伴侣')),
                ('photos', models.ManyToManyField(blank=True, default=None, null=True, related_name='records', to='SportRecord.SRPhoto', verbose_name='甜美一刻')),
                ('propertys', models.ManyToManyField(blank=True, default=None, related_name='records', to='SportRecord.SRProperty', verbose_name='使用的道具')),
                ('score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='SportRecord.srscore', verbose_name='打分')),
            ],
            options={
                'verbose_name': '记录',
                'verbose_name_plural': '记录',
            },
        ),
        migrations.CreateModel(
            name='SRRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='角色名称')),
                ('code', models.CharField(max_length=50, verbose_name='角色权限字符串')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=50, null=True, verbose_name='备注')),
                ('menu', models.ManyToManyField(blank=True, default=None, null=True, related_name='roles', to='SportRecord.SRMenu', verbose_name='菜单')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色s',
            },
        ),
        migrations.CreateModel(
            name='SRPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='地点名称')),
                ('type', models.CharField(blank=True, choices=[('1', '系统推荐'), ('2', '用户添加')], max_length=50, null=True, verbose_name='地点分类')),
                ('createTime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('uploadTime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='SportRecord.sruserprofile', verbose_name='创建人')),
            ],
            options={
                'verbose_name': '地点',
                'verbose_name_plural': '地点s',
            },
        ),
        migrations.AddField(
            model_name='srpartner',
            name='creater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='SportRecord.sruserprofile', verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='sruserprofile',
            name='role',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='SportRecord.SRRole', verbose_name='角色'),
        ),
    ]
