# Generated by Django 3.1.4 on 2025-03-26 15:08

from django.db import migrations, models
import django.utils.timezone
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sruserprofile',
            name='avator',
            field=models.ImageField(blank=True, default='', null=True, storage=system.storage.ImageStorage, upload_to='sportRecord/%Y/%m/%d', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='sruserprofile',
            name='birthday',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='出生日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sruserprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sruserprofile',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
