# Generated by Django 3.1.4 on 2025-03-26 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0002_auto_20250326_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sruserprofile',
            options={'verbose_name': '运动记录', 'verbose_name_plural': '运动记录'},
        ),
    ]
