# Generated by Django 3.2.25 on 2025-04-18 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0003_remove_srpartner_creater'),
    ]

    operations = [
        migrations.AddField(
            model_name='srpartner',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='SportRecord.sruserprofile', verbose_name='创建人'),
        ),
    ]
