# Generated by Django 3.1.4 on 2025-03-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0003_auto_20250326_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='sruserprofile',
            name='address',
            field=models.CharField(default='', max_length=50, verbose_name='地址'),
        ),
    ]
