# Generated by Django 3.2.25 on 2025-04-18 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0004_srpartner_creater'),
    ]

    operations = [
        migrations.AddField(
            model_name='srusersportrecord',
            name='place',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='SportRecord.srplace'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='srmood',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='心情图标'),
        ),
        migrations.AlterField(
            model_name='srscore',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='分数图标'),
        ),
        migrations.AlterField(
            model_name='srusersportrecord',
            name='measure',
            field=models.CharField(choices=[(1, '避孕套'), (2, '吃药'), (3, '无防护措施')], default=0, help_text='采取的安全措施，1-无保护措施,2-安全套，3-吃药', max_length=50, verbose_name='安全措施'),
        ),
    ]
