# Generated by Django 3.1.4 on 2025-03-26 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0004_sruserprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sruserprofile',
            name='birthday',
            field=models.DateField(default=datetime.datetime.now, verbose_name='出生日期'),
        ),
    ]
