# Generated by Django 3.1.4 on 2025-03-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0005_auto_20250326_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRSportCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='名称')),
                ('icon', models.FileField(blank=True, null=True, upload_to='sportRecord/category', verbose_name='图标')),
            ],
            options={
                'verbose_name': '运动类型',
                'verbose_name_plural': '运动类型',
            },
        ),
        migrations.CreateModel(
            name='SRUserSportRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='行为名称')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='行为地点')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='持续时间')),
            ],
            options={
                'verbose_name': '记录',
                'verbose_name_plural': '记录',
            },
        ),
        migrations.AlterModelOptions(
            name='sruserprofile',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
    ]
