# Generated by Django 3.1.4 on 2025-03-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0006_auto_20250326_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='srusersportrecord',
            name='type',
            field=models.CharField(blank=True, choices=[('za', 'za'), ('zw', 'zw'), ('my', 'my')], default='', max_length=50, null=True, verbose_name='类型'),
        ),
    ]
