# Generated by Django 3.2.25 on 2025-04-18 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0006_alter_srusersportrecord_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srusersportrecord',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='SportRecord.srplace', verbose_name='位置'),
        ),
    ]
