# Generated by Django 3.1.4 on 2025-03-27 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0007_srusersportrecord_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='srusersportrecord',
            name='categroy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SportRecord.srsportcategory', verbose_name='分类'),
        ),
    ]
