# Generated by Django 3.2.25 on 2025-04-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0007_alter_srusersportrecord_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srusersportrecord',
            name='measure',
            field=models.CharField(choices=[(1, '避孕套'), (2, '吃药'), (3, '无防护措施')], default='', help_text='采取的安全措施，1-安全套，2-吃药,3-无保护措施', max_length=50, verbose_name='安全措施'),
        ),
    ]
