# Generated by Django 3.1.4 on 2025-03-27 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0008_srusersportrecord_categroy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='srusersportrecord',
            old_name='categroy',
            new_name='category',
        ),
    ]
