# Generated by Django 3.1.4 on 2025-03-27 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0009_auto_20250327_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srusersportrecord',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SportRecord.srsportcategory', verbose_name='分类'),
        ),
    ]
