# Generated by Django 3.1.4 on 2025-03-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0010_auto_20250327_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='昵称')),
            ],
        ),
    ]
