# Generated by Django 3.1.4 on 2025-03-28 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0011_srpartner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='srpartner',
            options={'verbose_name': '伴侣', 'verbose_name_plural': '伴侣'},
        ),
        migrations.AddField(
            model_name='srpartner',
            name='avator',
            field=models.ImageField(default=None, upload_to='sportRecord/%Y/%m/%d', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='srpartner',
            name='birthday',
            field=models.DateField(default=datetime.datetime.now, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='srpartner',
            name='gender',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='', max_length=50, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='srpartner',
            name='mobile',
            field=models.CharField(default='', max_length=50, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='srpartner',
            name='remark',
            field=models.CharField(default='', max_length=50, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='srpartner',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='昵称'),
        ),
    ]
