# Generated by Django 3.1.4 on 2025-03-28 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0012_auto_20250328_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='sruserprofile',
            name='partner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='SportRecord.srpartner', verbose_name='伴侣'),
        ),
    ]
