# Generated by Django 3.2.25 on 2025-04-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0013_sruserprofile_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('icon', models.ImageField(default=None, upload_to='sportRecod/%Y%m%d', verbose_name='图标')),
                ('bgColor', models.CharField(max_length=50, verbose_name='背景色')),
            ],
            options={
                'verbose_name': '道具',
                'verbose_name_plural': '道具',
            },
        ),
        migrations.AlterField(
            model_name='srpartner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='srsportcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sruserprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='srusersportrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
