# Generated by Django 3.2.25 on 2025-04-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0014_auto_20250401_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRSystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='应用名称')),
                ('isInAppStoreView', models.BooleanField(verbose_name='是否在审核')),
            ],
            options={
                'verbose_name': '系统配置接口',
                'verbose_name_plural': '系统配置接口',
            },
        ),
    ]
