# Generated by Django 3.2.25 on 2025-04-03 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0015_srsystemconfig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='srsystemconfig',
            old_name='isInAppStoreView',
            new_name='isInReView',
        ),
    ]
