# Generated by Django 3.2.25 on 2025-04-03 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0016_rename_isinappstoreview_srsystemconfig_isinreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='srproperty',
            name='record',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='propertys', to='SportRecord.srusersportrecord', verbose_name='所属运动'),
        ),
    ]
