# Generated by Django 3.2.25 on 2025-04-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0018_alter_srproperty_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='srproperty',
            name='record',
        ),
        migrations.RemoveField(
            model_name='srusersportrecord',
            name='category',
        ),
        migrations.AddField(
            model_name='srusersportrecord',
            name='propertys',
            field=models.ManyToManyField(blank=True, default=None, related_name='records', to='SportRecord.SRProperty', verbose_name='使用的道具'),
        ),
    ]
