# Generated by Django 3.2.25 on 2025-04-03 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0019_auto_20250403_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='心情')),
                ('icon', models.ImageField(blank=True, default=None, null=True, upload_to='sportRecord/%Y/%m/%d', verbose_name='心情图标')),
            ],
            options={
                'verbose_name': '心情',
                'verbose_name_plural': '心情',
                'db_table': 'srmood',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SRScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='分数')),
                ('score', models.SmallIntegerField(verbose_name='分数1-5')),
                ('icon', models.ImageField(blank=True, default=None, null=True, upload_to='sportRecord/%Y/%m/%d', verbose_name='分数图标')),
            ],
            options={
                'verbose_name': '分数',
                'verbose_name_plural': '分数',
                'db_table': 'srscore',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='srusersportrecord',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SportRecord.srpartner', verbose_name='伴侣'),
        ),
        migrations.AlterField(
            model_name='srsportcategory',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='sportRecord/%Y/%m/%d', verbose_name='图标'),
        ),
    ]
