# Generated by Django 3.2.25 on 2025-04-03 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0020_auto_20250403_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srusersportrecord',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='SportRecord.srpartner', verbose_name='伴侣'),
        ),
    ]
