# Generated by Django 3.2.25 on 2025-04-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0021_alter_srusersportrecord_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='srusersportrecord',
            name='partner',
        ),
        migrations.AddField(
            model_name='srusersportrecord',
            name='partner',
            field=models.ManyToManyField(blank=True, null=True, related_name='records', to='SportRecord.SRPartner', verbose_name='伴侣'),
        ),
    ]
