# Generated by Django 3.2.25 on 2025-04-03 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0022_auto_20250403_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRClothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('icon', models.ImageField(default=None, upload_to='sportRecod/%Y%m%d', verbose_name='图标')),
                ('bgColor', models.CharField(max_length=50, verbose_name='背景色')),
            ],
            options={
                'verbose_name': '服装',
                'verbose_name_plural': '服装',
            },
        ),
        migrations.AddField(
            model_name='srusersportrecord',
            name='mood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='SportRecord.srmood', verbose_name='心情'),
        ),
        migrations.AddField(
            model_name='srusersportrecord',
            name='remark',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='srusersportrecord',
            name='score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='SportRecord.srscore', verbose_name='打分'),
        ),
    ]
