# Generated by Django 3.2.25 on 2025-04-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0023_auto_20250403_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='srusersportrecord',
            name='measure',
            field=models.SmallIntegerField(default=0, verbose_name='安全措施'),
        ),
    ]
