# Generated by Django 3.2.25 on 2025-04-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0024_srusersportrecord_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srusersportrecord',
            name='measure',
            field=models.SmallIntegerField(default=0, help_text='采取的安全措施，1-无保护措施,2-安全套，3-吃药', verbose_name='安全措施'),
        ),
    ]
