# Generated by Django 3.2.25 on 2025-04-03 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0025_alter_srusersportrecord_measure'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRShootPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeName', models.CharField(max_length=50, verbose_name='射精位置')),
            ],
            options={
                'verbose_name': '射精位置',
                'verbose_name_plural': '射精位置',
            },
        ),
        migrations.AddField(
            model_name='srusersportrecord',
            name='clothings',
            field=models.ManyToManyField(default=None, related_name='records', to='SportRecord.SRClothing', verbose_name='服装'),
        ),
        migrations.AddField(
            model_name='srusersportrecord',
            name='highTime',
            field=models.SmallIntegerField(default=0, verbose_name='高潮次数'),
        ),
        migrations.AddField(
            model_name='srusersportrecord',
            name='highTimePartner',
            field=models.SmallIntegerField(default=0, verbose_name='伴侣高潮次数'),
        ),
        migrations.AddField(
            model_name='srusersportrecord',
            name='isHigh',
            field=models.BooleanField(default=False, verbose_name='是否潮吹'),
        ),
        migrations.AddField(
            model_name='srusersportrecord',
            name='isSender',
            field=models.BooleanField(default=True, verbose_name='是否是发起方'),
        ),
        migrations.AddField(
            model_name='srusersportrecord',
            name='shootPlace',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SportRecord.srshootplace', verbose_name='射精位置'),
        ),
    ]
