# Generated by Django 3.2.25 on 2025-04-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0026_auto_20250403_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='sportRecord/%Y/%m/%d', verbose_name='图片')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
            },
        ),
        migrations.AddField(
            model_name='srusersportrecord',
            name='photos',
            field=models.ManyToManyField(default=None, related_name='records', to='SportRecord.SRPhoto', verbose_name='甜美一刻'),
        ),
    ]
