# Generated by Django 3.2.25 on 2025-04-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0027_auto_20250403_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srusersportrecord',
            name='clothings',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='records', to='SportRecord.SRClothing', verbose_name='服装'),
        ),
        migrations.AlterField(
            model_name='srusersportrecord',
            name='photos',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='records', to='SportRecord.SRPhoto', verbose_name='甜美一刻'),
        ),
    ]
