# Generated by Django 3.2.25 on 2025-04-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0028_auto_20250403_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srclothing',
            name='bgColor',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='背景色'),
        ),
        migrations.AlterField(
            model_name='srproperty',
            name='bgColor',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='背景色'),
        ),
    ]
