# Generated by Django 3.2.25 on 2025-04-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0029_auto_20250403_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='sruserprofile',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='sruserprofile',
            name='password',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='sruserprofile',
            name='username',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='用户名'),
        ),
    ]
