# Generated by Django 3.2.25 on 2025-04-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0030_auto_20250407_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('icon', models.CharField(max_length=50, verbose_name='菜单图标')),
                ('parent_id', models.IntegerField(verbose_name='父菜单id')),
                ('order_num', models.IntegerField(verbose_name='显示顺序')),
                ('path', models.CharField(max_length=50, verbose_name='路由地址')),
                ('component', models.CharField(max_length=50, verbose_name='组件路径')),
                ('menu_type', models.CharField(max_length=50, verbose_name='菜单类型（M 目录 C 菜单 F 按钮）')),
                ('perms', models.CharField(max_length=50, verbose_name='权限标示')),
                ('create_time', models.DateField(blank=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateField(blank=True, null=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=50, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
            },
        ),
        migrations.CreateModel(
            name='SRRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='角色名称')),
                ('code', models.CharField(max_length=50, verbose_name='角色权限字符串')),
                ('create_time', models.DateField(blank=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateField(blank=True, null=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=50, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色s',
            },
        ),
        migrations.AddField(
            model_name='sruserprofile',
            name='menu',
            field=models.ManyToManyField(default=None, to='SportRecord.SRMenu', verbose_name='菜单'),
        ),
        migrations.AddField(
            model_name='sruserprofile',
            name='role',
            field=models.ManyToManyField(default=None, to='SportRecord.SRRole', verbose_name='角色'),
        ),
    ]
