# Generated by Django 3.2.25 on 2025-04-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0031_auto_20250407_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sruserprofile',
            name='menu',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='SportRecord.SRMenu', verbose_name='菜单'),
        ),
        migrations.AlterField(
            model_name='sruserprofile',
            name='role',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='SportRecord.SRRole', verbose_name='角色'),
        ),
    ]
