# Generated by Django 3.2.25 on 2025-04-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0032_auto_20250407_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sruserprofile',
            name='menu',
        ),
        migrations.AddField(
            model_name='srrole',
            name='menu',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='SportRecord.SRMenu', verbose_name='菜单'),
        ),
    ]
