# Generated by Django 3.2.25 on 2025-04-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0033_auto_20250407_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srmenu',
            name='component',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='组件路径'),
        ),
        migrations.AlterField(
            model_name='srmenu',
            name='perms',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='权限标示'),
        ),
    ]
