# Generated by Django 3.2.25 on 2025-04-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0034_auto_20250407_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='sruserprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], default='', max_length=50, null=True, verbose_name='性别'),
        ),
    ]
