# Generated by Django 3.2.25 on 2025-04-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0035_sruserprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='sruserprofile',
            name='status',
            field=models.BooleanField(default=True, verbose_name='是否禁用 0-禁用 1-正常'),
        ),
    ]
