# Generated by Django 3.2.25 on 2025-04-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0036_sruserprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sruserprofile',
            name='remark',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='sruserprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='地址'),
        ),
    ]
