# Generated by Django 3.2.25 on 2025-04-09 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0037_auto_20250409_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sruserprofile',
            name='partner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='SportRecord.srpartner', verbose_name='伴侣'),
        ),
    ]
