# Generated by Django 3.2.25 on 2025-04-09 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0038_alter_sruserprofile_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sruserprofile',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2025, 4, 9, 20, 53, 12, 266230), verbose_name='出生日期'),
        ),
    ]
