# Generated by Django 3.2.25 on 2025-04-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0039_alter_sruserprofile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sruserprofile',
            name='birthday',
            field=models.DateField(auto_now=True, verbose_name='出生日期'),
        ),
    ]
