# Generated by Django 3.2.25 on 2025-04-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportRecord', '0041_auto_20250410_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srrole',
            name='menu',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='roles', to='SportRecord.SRMenu', verbose_name='菜单'),
        ),
    ]
