# Generated by Django 2.2.6 on 2019-11-08 00:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default='', max_length=255)),
                ('image', models.CharField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
                ('desciption', models.CharField(default='', max_length=255)),
                ('category', models.CharField(default='', max_length=255)),
                ('author', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('author_link', models.CharField(default='', max_length=255)),
                ('update_time', models.DateField(default=datetime.datetime(2019, 11, 8, 0, 43, 59, 666289, tzinfo=utc), max_length=255)),
                ('downloadurl', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(default='', editable=False, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=10)),
                ('nickname', models.CharField(default='', max_length=50)),
                ('avtor', models.URLField()),
                ('wx_openid', models.CharField(default='', max_length=100)),
                ('wx_avtor', models.CharField(default='', max_length=100)),
                ('wx_access_token', models.CharField(default='', max_length=100)),
                ('wx_unionid', models.CharField(default='', max_length=100)),
                ('wx_refresh_token', models.CharField(default='', max_length=100)),
                ('wx_city', models.CharField(default='', max_length=100)),
                ('wx_headimgurl', models.CharField(default='', max_length=100)),
                ('wx_language', models.CharField(default='', max_length=100)),
                ('wx_province', models.CharField(default='', max_length=100)),
                ('wx_nickname', models.CharField(default='', max_length=100)),
                ('wx_sex', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.Contact')),
            ],
        ),
    ]
