# Generated by Django 2.2.6 on 2022-07-18 16:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_url', models.CharField(default='', max_length=255)),
                ('des', models.CharField(default='', max_length=1000)),
                ('image', models.CharField(default='', max_length=255)),
                ('category', models.CharField(default='', max_length=255)),
                ('author', models.CharField(default='', max_length=255)),
                ('status', models.CharField(default='', max_length=255)),
                ('update_time', models.DateField(default=django.utils.timezone.now, max_length=255)),
                ('latest_chapter_name', models.CharField(default='', max_length=255)),
                ('latest_chapter_url', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=1000)),
                ('download_url', models.CharField(default='', max_length=255)),
                ('isUpload', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BookSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookids', models.CharField(default='', max_length=255)),
                ('bookNames', models.CharField(default='', max_length=255)),
                ('userid', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BuglyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='', max_length=255)),
                ('app_version', models.CharField(default='', max_length=255)),
                ('app_ext', models.CharField(default='', max_length=255)),
                ('app_text', models.CharField(default='', max_length=255)),
                ('create_At', models.DateField(default=django.utils.timezone.now, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default='', max_length=255)),
                ('count', models.IntegerField(default=1)),
                ('haveInsert', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('title', models.CharField(default='', max_length=200, verbose_name='标题')),
                ('agreed', models.BooleanField(default=False, verbose_name='审核状态')),
            ],
            options={
                'verbose_name_plural': '测试',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=10)),
                ('nickname', models.CharField(default='', max_length=50)),
                ('avtor', models.URLField()),
                ('wx_openid', models.CharField(default='', max_length=100)),
                ('wx_avtor', models.CharField(default='', max_length=100)),
                ('wx_access_token', models.CharField(default='', max_length=100)),
                ('wx_unionid', models.CharField(default='', max_length=100)),
                ('wx_refresh_token', models.CharField(default='', max_length=100)),
                ('wx_city', models.CharField(default='', max_length=100)),
                ('wx_headimgurl', models.CharField(default='', max_length=100)),
                ('wx_language', models.CharField(default='', max_length=100)),
                ('wx_province', models.CharField(default='', max_length=100)),
                ('wx_nickname', models.CharField(default='', max_length=100)),
                ('wx_sex', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('path', models.CharField(default='', max_length=255)),
                ('chaperIdx', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.Book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='bookCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.BookCategory'),
        ),
    ]
