# Generated by Django 2.2.6 on 2019-11-08 00:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='update_time',
            field=models.DateField(default=datetime.datetime(2019, 11, 8, 0, 44, 23, 30203, tzinfo=utc), max_length=255),
        ),
    ]
