# Generated by Django 2.2.6 on 2019-11-06 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='update_time',
            field=models.DateField(default=datetime.datetime(2019, 11, 6, 3, 45, 44, 921165), max_length=255),
        ),
    ]
