# Generated by Django 2.2.6 on 2019-11-08 08:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_auto_20191108_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='update_time',
            field=models.DateField(default=datetime.datetime(2019, 11, 8, 8, 49, 54, 266236, tzinfo=utc), max_length=255),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('path', models.CharField(default='', max_length=255)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.Book')),
            ],
        ),
    ]
