# Generated by Django 2.2.6 on 2019-11-13 07:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_auto_20191113_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='des',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='book',
            name='update_time',
            field=models.DateField(default=datetime.datetime(2019, 11, 13, 7, 10, 35, 790030, tzinfo=utc), max_length=255),
        ),
    ]
