# Generated by Django 2.2.6 on 2019-11-08 13:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_auto_20191108_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pic',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='update_time',
            field=models.DateField(default=datetime.datetime(2019, 11, 8, 13, 9, 39, 275950, tzinfo=utc), max_length=255),
        ),
    ]
