# Generated by Django 2.1.8 on 2019-11-18 15:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_auto_20191113_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='update_time',
            field=models.DateField(default=datetime.datetime(2019, 11, 18, 15, 19, 1, 432997, tzinfo=utc), max_length=255),
        ),
    ]
