# Generated by Django 2.2.6 on 2019-11-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_auto_20191105_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=10)),
                ('nickname', models.CharField(default='', max_length=50)),
                ('avtor', models.URLField()),
                ('wx_openid', models.CharField(default='', max_length=100)),
                ('wx_avtor', models.CharField(default='', max_length=100)),
                ('wx_access_token', models.CharField(default='', max_length=100)),
                ('wx_unionid', models.CharField(default='', max_length=100)),
                ('wx_refresh_token', models.CharField(default='', max_length=100)),
                ('wx_city', models.CharField(default='', max_length=100)),
                ('wx_headimgurl', models.CharField(default='', max_length=100)),
                ('wx_language', models.CharField(default='', max_length=100)),
                ('wx_province', models.CharField(default='', max_length=100)),
                ('wx_nickname', models.CharField(default='', max_length=100)),
                ('wx_sex', models.IntegerField(default=0)),
            ],
        ),
    ]
