# Generated by Django 2.2.6 on 2019-11-08 14:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0004_auto_20191108_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='update_time',
            field=models.DateField(default=datetime.datetime(2019, 11, 8, 14, 30, 30, 272817, tzinfo=utc), max_length=255),
        ),
    ]
