# Generated by Django 2.2.6 on 2019-11-21 13:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_auto_20191121_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='update_time',
            field=models.DateField(default=datetime.datetime(2019, 11, 21, 13, 43, 43, 89650, tzinfo=utc), max_length=255),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
