# Generated by Django 2.2.6 on 2019-11-08 15:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_auto_20191108_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='update_time',
            field=models.DateField(default=datetime.datetime(2019, 11, 8, 15, 13, 1, 571343, tzinfo=utc), max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='bookCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TestModel.BookCategory'),
            preserve_default=False,
        ),
    ]
