# Generated by Django 2.2.6 on 2019-11-08 15:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0006_auto_20191108_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='update_time',
            field=models.DateField(default=datetime.datetime(2019, 11, 8, 15, 14, 3, 538511, tzinfo=utc), max_length=255),
        ),
    ]
