# Generated by Django 2.2.6 on 2019-11-21 13:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0006_auto_20191121_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chatperIdx',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='update_time',
            field=models.DateField(default=datetime.datetime(2019, 11, 21, 13, 45, 4, 619187, tzinfo=utc), max_length=255),
        ),
    ]
