# Generated by Django 2.2.6 on 2019-11-21 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0007_auto_20191121_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='index',
        ),
        migrations.AlterField(
            model_name='book',
            name='update_time',
            field=models.DateField(default=datetime.datetime(2019, 11, 21, 13, 47, 39, 787542, tzinfo=utc), max_length=255),
        ),
    ]
