# Generated by Django 2.2.6 on 2019-11-21 14:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0008_auto_20191121_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='chatperIdx',
            new_name='chaperIdx',
        ),
        migrations.AlterField(
            model_name='book',
            name='update_time',
            field=models.DateField(default=datetime.datetime(2019, 11, 21, 14, 0, 44, 501775, tzinfo=utc), max_length=255),
        ),
    ]
