# Generated by Django 2.2.6 on 2019-11-21 14:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0009_auto_20191121_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='update_time',
            field=models.DateField(default=datetime.datetime(2019, 11, 21, 14, 3, 11, 539076, tzinfo=utc), max_length=255),
        ),
    ]
