# Generated by Django 2.2.6 on 2019-11-22 14:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0010_auto_20191121_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isUpload',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='update_time',
            field=models.DateField(default=datetime.datetime(2019, 11, 22, 14, 11, 15, 808407, tzinfo=utc), max_length=255),
        ),
    ]
