# Generated by Django 2.1.8 on 2019-11-22 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0004_auto_20191118_1519'),
        ('TestModel', '0010_auto_20191121_1403'),
    ]

    operations = [
    ]
