# Generated by Django 2.1.8 on 2019-11-22 06:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0011_merge_20191122_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='update_time',
            field=models.DateField(default=datetime.datetime(2019, 11, 22, 6, 29, 29, 753753, tzinfo=utc), max_length=255),
        ),
    ]
