# Generated by Django 2.2.6 on 2019-11-28 09:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0012_auto_20191128_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='update_time',
            field=models.DateField(default=datetime.datetime(2019, 11, 28, 9, 3, 47, 727739, tzinfo=utc), max_length=255),
        ),
    ]
