# Generated by Django 2.2.6 on 2019-11-28 09:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0013_auto_20191128_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookids', models.CharField(default='', max_length=255)),
                ('bookNames', models.CharField(default='', max_length=255)),
                ('userid', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='update_time',
            field=models.DateField(default=datetime.datetime(2019, 11, 28, 9, 31, 24, 106936, tzinfo=utc), max_length=255),
        ),
    ]
