# Generated by Django 2.1.8 on 2019-11-28 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0014_auto_20191128_0931'),
        ('TestModel', '0012_auto_20191122_0629'),
    ]

    operations = [
    ]
