# Generated by Django 2.2.6 on 2019-11-28 10:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0015_merge_20191128_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='haveInsert',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='update_time',
            field=models.DateField(default=datetime.datetime(2019, 11, 28, 10, 17, 45, 549681, tzinfo=utc), max_length=255),
        ),
    ]
