# Generated by Django 2.2.6 on 2020-09-19 02:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0017_auto_20200919_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='update_time',
            field=models.DateField(default=datetime.datetime(2020, 9, 19, 2, 24, 30, 156273, tzinfo=utc), max_length=255),
        ),
    ]
