# Generated by Django 2.2.6 on 2020-09-19 02:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0018_auto_20200919_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='update_time',
            field=models.DateField(default=datetime.datetime(2020, 9, 19, 2, 26, 58, 861136, tzinfo=utc), max_length=255),
        ),
    ]
