# Generated by Django 2.2.6 on 2020-09-19 03:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0019_auto_20200919_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='update_time',
            field=models.DateField(default=django.utils.timezone.now, max_length=255),
        ),
    ]
