# Generated by Django 2.2.6 on 2020-12-13 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0020_auto_20200919_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuglyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='', max_length=255)),
                ('app_version', models.CharField(default='', max_length=255)),
                ('app_text', models.CharField(default='', max_length=255)),
                ('create_At', models.DateField(default=django.utils.timezone.now, max_length=255)),
            ],
        ),
    ]
