# Generated by Django 3.1.5 on 2021-01-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0022_buglydata_app_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='agreed',
            field=models.BooleanField(default=False, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=20, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='标题'),
        ),
    ]
