# Generated by Django 3.1.5 on 2021-01-08 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0023_auto_20210108_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name_plural': '测试'},
        ),
    ]
