# Generated by Django 2.2.6 on 2020-09-19 11:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import system.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DKFeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DKVersionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('des', models.CharField(max_length=150)),
                ('date', models.DateField(default=django.utils.timezone.now, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default=0, max_length=10)),
                ('message', models.CharField(default='success', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(default='', max_length=100)),
                ('picture', models.ImageField(storage=system.storage.ImageStorage(), upload_to='img/%Y/%m/%d')),
                ('feedBackInfo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DailyClock.DKFeedBack')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
