# Generated by Django 3.2.25 on 2025-04-01 15:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import system.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DKFeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now, max_length=255)),
                ('reply', models.CharField(default='', max_length=255)),
                ('remark', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': '打卡反馈',
                'verbose_name_plural': '打卡反馈',
            },
        ),
        migrations.CreateModel(
            name='DKFonts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('font_name', models.CharField(default='', max_length=30)),
                ('font_bold_name', models.CharField(default='', max_length=20)),
                ('url', models.CharField(default='', max_length=100)),
                ('file', models.FileField(default=None, storage=system.storage.ImageStorage, upload_to='fonts/', verbose_name='上传文件')),
            ],
            options={
                'verbose_name': '字体设置',
                'verbose_name_plural': '字体设置',
            },
        ),
        migrations.CreateModel(
            name='DKJiTang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=255)),
                ('url', models.CharField(default='', max_length=255)),
                ('wordsInfo', models.CharField(default='', max_length=255)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('objectId', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': '鸡汤',
                'verbose_name_plural': '鸡汤',
                'db_table': 'jitang',
            },
        ),
        migrations.CreateModel(
            name='DKVersionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('des', models.CharField(max_length=150)),
                ('date', models.DateField(default=django.utils.timezone.now, max_length=10)),
            ],
            options={
                'verbose_name': '版本历史',
                'verbose_name_plural': '版本历史',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default=0, max_length=10)),
                ('message', models.CharField(default='success', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(default='', max_length=100)),
                ('picture', models.ImageField(storage=system.storage.ImageStorage(), upload_to='img/%Y/%m/%d')),
                ('feedBackInfo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DailyClock.dkfeedback')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
