# Generated by Django 2.2.6 on 2020-10-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyClock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DKFonts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('font_name', models.CharField(default='', max_length=30)),
                ('font_bold_name', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
