# Generated by Django 2.2.6 on 2022-08-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyClock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dkfeedback',
            name='reply',
            field=models.CharField(default='', max_length=255),
        ),
    ]
