# Generated by Django 2.2.6 on 2020-09-19 03:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DailyClock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DKVersionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('des', models.CharField(max_length=150)),
                ('date', models.DateField(default=django.utils.timezone.now, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='dailyClock')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.RenameField(
            model_name='dkfeedback',
            old_name='phoneNumber',
            new_name='phone',
        ),
    ]
