# Generated by Django 2.2.6 on 2020-10-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyClock', '0002_dkfonts'),
    ]

    operations = [
        migrations.AddField(
            model_name='dkfonts',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
