# Generated by Django 2.2.6 on 2020-09-19 04:34

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('DailyClock', '0002_auto_20200919_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(storage=system.storage.ImageStorage(), upload_to='img/%Y/%m/%d'),
        ),
    ]
