# Generated by Django 3.1 on 2023-06-20 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DailyClock', '0002_dkfeedback_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dkfeedback',
            options={'verbose_name': '打卡反馈', 'verbose_name_plural': '打卡反馈'},
        ),
        migrations.AlterModelOptions(
            name='dkfonts',
            options={'verbose_name': '字体设置', 'verbose_name_plural': '字体设置'},
        ),
        migrations.AlterModelOptions(
            name='dkjitang',
            options={'verbose_name': '鸡汤', 'verbose_name_plural': '鸡汤'},
        ),
        migrations.AlterModelOptions(
            name='dkversionhistory',
            options={'verbose_name': '版本历史', 'verbose_name_plural': '版本历史'},
        ),
    ]
