# Generated by Django 3.1.4 on 2023-05-19 06:33

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('DailyClock', '0002_dkfeedback_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dkfeedback',
            options={'verbose_name': '打卡反馈', 'verbose_name_plural': '打卡反馈'},
        ),
        migrations.AlterModelOptions(
            name='dkfonts',
            options={'verbose_name': '字体设置', 'verbose_name_plural': '字体设置'},
        ),
        migrations.AlterModelOptions(
            name='dkjitang',
            options={'verbose_name': '鸡汤', 'verbose_name_plural': '鸡汤'},
        ),
        migrations.AlterModelOptions(
            name='dkversionhistory',
            options={'verbose_name': '版本历史', 'verbose_name_plural': '版本历史'},
        ),
        migrations.AddField(
            model_name='dkfonts',
            name='file',
            field=models.FileField(default=None, storage=system.storage.ImageStorage, upload_to='fonts/', verbose_name='上传文件'),
        ),
    ]
