# Generated by Django 2.2.6 on 2020-12-13 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyClock', '0003_dkfonts_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DKJiTang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=255)),
                ('url', models.CharField(default='', max_length=255)),
                ('wordsInfo', models.CharField(default='', max_length=255)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('objectId', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'jitang',
            },
        ),
    ]
