# Generated by Django 3.1 on 2023-06-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DailyClock', '0003_auto_20230620_1518'),
        ('DailyClock', '0003_auto_20230519_0633'),
    ]

    operations = [
    ]
