# Generated by Django 3.1 on 2023-06-20 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DailyClock', '0004_merge_20230620_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dkfonts',
            name='file',
        ),
    ]
