# Generated by Django 3.1 on 2023-06-21 16:58

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('DailyClock', '0005_remove_dkfonts_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='dkfonts',
            name='file',
            field=models.FileField(default=None, storage=system.storage.ImageStorage(), upload_to='fonts/', verbose_name='上传文件'),
        ),
    ]
