# Generated by Django 2.2.6 on 2020-09-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyClock', '0006_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='message',
            field=models.CharField(default='success', max_length=20),
        ),
        migrations.AddField(
            model_name='result',
            name='status',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
