# Generated by Django 3.1.4 on 2023-09-18 19:40

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('DailyClock', '0006_dkfonts_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dkfonts',
            name='file',
            field=models.FileField(default=None, storage=system.storage.ImageStorage, upload_to='fonts/', verbose_name='上传文件'),
        ),
    ]
