# Generated by Django 3.1.4 on 2023-09-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyClock', '0007_auto_20230918_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='dkfeedback',
            name='remark',
            field=models.CharField(default='', max_length=255),
        ),
    ]
