# Generated by Django 2.2.6 on 2020-09-19 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DailyClock', '0007_auto_20200919_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='feedBackInfo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='feedBack', to='DailyClock.DKFeedBack'),
        ),
    ]
