# Generated by Django 2.2.6 on 2020-09-19 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DailyClock', '0008_profile_feedbackinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='feedBackInfo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='DailyClock.DKFeedBack'),
        ),
    ]
