# Generated by Django 2.2.6 on 2020-09-19 07:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DailyClock', '0009_auto_20200919_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='dkfeedback',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='feedBackInfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DailyClock.DKFeedBack'),
        ),
    ]
