# Generated by Django 2.2.6 on 2020-09-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyClock', '0010_auto_20200919_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
