# Generated by Django 3.1.5 on 2021-01-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TYMetro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
    ]
