# Generated by Django 2.2.6 on 2022-09-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TYMetro', '0002_auto_20220906_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
