# Generated by Django 3.1.4 on 2021-01-18 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TYMetro', '0005_auto_20210108_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_text', models.CharField(blank=True, max_length=1000, verbose_name='反馈')),
                ('feed_imgs', models.CharField(blank=True, max_length=1000, verbose_name='图片')),
                ('create_at', models.DateField(blank=True, default=django.utils.timezone.now, max_length=255)),
                ('update_at', models.DateField(blank=True, default=django.utils.timezone.now, max_length=255)),
            ],
            options={
                'verbose_name': '问题反馈',
                'verbose_name_plural': '问题反馈',
            },
        ),
    ]
