# Generated by Django 3.1.4 on 2021-11-08 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('ZhuaZhou', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', filer.fields.image.FilerImageField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_image', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': '首页轮播图',
                'verbose_name_plural': '首页轮播图',
            },
        ),
    ]
