# Generated by Django 3.1.4 on 2021-11-08 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('ZhuaZhou', '0002_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='img',
            field=filer.fields.image.FilerImageField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_image', to=settings.FILER_IMAGE_MODEL, verbose_name='抓周图片'),
        ),
    ]
